INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, MOBILE, SEX ) 
VALUES('Pieter', 'Amsterdam', 96215489652, 'MALE' );

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, MOBILE, SEX ) 
VALUES('KEY', 'STERM', 8974512598, 'MALE' );

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, MOBILE, SEX ) 
VALUES('LAUS', 'FATER', 5481489652, 'MALE' );